services:
  # 1. BROKER (Infraestructura)
  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: local_rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    shm_size: 2gb
    volumes:
      - ./docker-data/rabbitmq:/var/lib/rabbitmq
    networks:
      - micro-events-net
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  # 2. API GATEWAY (Productor)
  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    ports:
      - '3000:3000'
    environment:
      RABBITMQ_URI: amqp://user:password@rabbitmq:5672
      RABBITMQ_QUEUE: notifications_queue
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - micro-events-net

  # 3. EMAIL WORKER (Consumidor)
  email-worker:
    build:
      context: .
      dockerfile: apps/email-worker/Dockerfile
    environment:
      RABBITMQ_URI: amqp://user:password@rabbitmq:5672
      RABBITMQ_QUEUE: notifications_queue
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - micro-events-net

networks:
  micro-events-net:
    driver: bridge
