name: Build and Publish Docker Images

on:
  push:
    branches: ['master', 'main']

env:
  REGISTRY: ghcr.io
  # github.repository es "usuario/repo"
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Permiso vital para subir al registro

    strategy:
      fail-fast: false
      matrix:
        include:
          - service: api-gateway
            dockerfile: apps/api-gateway/Dockerfile
          - service: email-worker
            dockerfile: apps/email-worker/Dockerfile

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          # Genera nombres: ghcr.io/usuario/repo/api-gateway
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.service }}
          tags: |
            type=raw,value=latest
            type=sha,format=long

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . # IMPORTANTE: Contexto raíz del monorepo
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
